// playground/react/App.jsx
/* eslint-disable no-restricted-globals */
import React from 'react';
// eslint-disable-next-line
import { A11y, Navigation, Pagination, Scrollbar, Mousewheel } from 'swiper';
// eslint-disable-next-line
import { Swiper, SwiperSlide } from 'swiper/react/swiper-react';

const App = () => {
  return (
    <main>
      <h1>Swipperjs :</h1>
      <Swiper
        activeLastSlideClass={false}
        modules={[Pagination, Mousewheel, Navigation, Scrollbar]}
        onSwiper={(swiper) => (window.swiper = swiper)}
        slidesPerView={3.3}
        threshold={2}
        spaceBetween={10}
        navigation
        scrollbar
        mousewheel={{ forceToAxis: true, sensitivity: 0.1, releaseOnEdges: true }}
        pagination={{ clickable: true }}
      >
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
        <SwiperSlide>Slide 4</SwiperSlide>
        <SwiperSlide>Slide 5</SwiperSlide>
      </Swiper>

      <h1>@abasb75/swiper with activeLastSlideClass</h1>
      <Swiper
        activeLastSlideClass={true}
        rewind={true}
        modules={[Pagination, Mousewheel, Navigation, Scrollbar]}
        onSwiper={(swiper) => (window.swiper = swiper)}
        slidesPerView={3.3}
        threshold={2}
        spaceBetween={10}
        navigation
        scrollbar
        mousewheel={{ forceToAxis: true, sensitivity: 0.1, releaseOnEdges: true }}
        pagination={{ clickable: true }}
      >
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
        <SwiperSlide>Slide 3</SwiperSlide>
        <SwiperSlide>Slide 4</SwiperSlide>
        <SwiperSlide>Slide 5</SwiperSlide>
      </Swiper>
    </main>
  );
};

export default App;

// playground/vue/App.vue
<template>
  <main>
    <swiper
      @swiper="onSwiper"
      :slidesPerView="3"
      :spaceBetween="50"
      navigation
      :scrollbar="{ draggable: true }"
      :pagination="{ clickable: true }"
      :modules="modules"
    >
      <swiper-slide><innerComp>Slide 1</innerComp></swiper-slide>
      <swiper-slide>Slide 2</swiper-slide>
      <swiper-slide>Slide 3</swiper-slide>
      <swiper-slide>Slide 4</swiper-slide>
      <swiper-slide>Slide 5</swiper-slide>
      <swiper-slide>Slide 6</swiper-slide>
      <swiper-slide>Slide 7</swiper-slide>
      <swiper-slide>Slide 8</swiper-slide>
      <swiper-slide>Slide 9</swiper-slide>
      <swiper-slide>Slide 10</swiper-slide>
    </swiper>
  </main>
</template>
<script>
// eslint-disable-next-line
import { Navigation, Pagination, Scrollbar, A11y } from '@abasb75/swiper';
// eslint-disable-next-line
import { Swiper, SwiperSlide } from '@abasb75/swiper/vue/swiper-vue.js';
import innerComp from './innerComp.vue';

export default {
  components: {
    Swiper,
    SwiperSlide,
    innerComp,
  },

  setup() {
    const onSwiper = (swiper) => {
      window.swiper = swiper;
    };
    return {
      modules: [Navigation, Pagination, Scrollbar, A11y],
      onSwiper,
    };
  },
};
</script>
